[tools]
bun = "latest"
podman = "latest"
rust = "latest"

[tasks.pre-commit]
depends = ["format", "lint", "typecheck", "test"]

[tasks.dev]
depends = ["dev-server", "dev-web"]

[tasks.build]
depends = ["build-server", "build-web"]

[tasks.format]
depends = ["format-rs"]

[tasks.lint]
depends = ["lint-rs"]

[tasks.typecheck]
depends = ["typecheck-rs"]

[tasks.test]
depends = ["test-server"]

[tasks.dev-server]
dir = "recipe-scraper-server"
run = "cargo watch -x run"

[tasks.dev-web]
dir = "recipe-scraper-web"
run = "bun run dev"

[tasks.build-server]
dir = "recipe-scraper-server"
run = "cargo build --release"

[tasks.build-web]
dir = "recipe-scraper-web"
run = "bun run build"

[tasks.format-rs]
dir = "recipe-scraper-server"
run = "cargo fmt"

[tasks.lint-rs]
dir = "recipe-scraper-server"
run = "cargo check"
wait_for = ["format-rs"]

[tasks.typecheck-rs]
dir = "recipe-scraper-server"
run = "cargo clippy"
wait_for = ["format-rs"]

[tasks.test-server]
dir = "recipe-scraper-server"
run = "cargo test"
wait_for = ["lint-rs", "typecheck-rs"]

[tasks.tor]
run = "podman run -d --rm --name tor-socks -p 9050:9050 dperson/torproxy"
