[package]
name = "recipe-crawler-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
prost = "0.14.3"
rand = "0.8"
quick-xml = "0.37"
reqwest = { version = "0.12", features = ["gzip", "rustls-tls", "socks"], default-features = false }
scraper = "0.23"
tokio = { version = "1.52.3", features = ["full"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"

[dev-dependencies]
wiremock = "0.6"

[build-dependencies]
tonic-prost-build = "0.14.6"
